num_train: 20000
num_val: 250
batch_size: null
trainable_params: 10402817
num_gpus: 1
gpu_ids:
- 0
num_workers: 10
torch_version: 2.9.1+cu128
lightning_version: 2.5.2
cuda_version: '12.8'
hostname: compute-gpu-0-1.local
out_dir: /home/xucapfwi/hepattn/src/hepattn/experiments/colliderml/logs/ColliderML_Calo_Clustering_20260802-T234016
log_url: https://www.comet.com/finnbarwilson/colliderml-calo-clustering/bd46b0b596634823aee624a30c8c9c74
slurm_job_id: SLURM_48169
